const menuConfig = {
  siteUrl: "https://kerroggu.github.io/SakeMenu/",
  menuCsvPath: "./menu.csv",
  menuVersion: "2026-05-21-gakki-alterna",
  gasAppUrl: "",
  columns: {
    id: ["id", "itemid", "slug"],
    name: ["name", "銘柄", "銘柄名", "酒名", "brand", "label"],
    searchName: ["searchname", "search_name", "検索名", "別名", "name2"],
    image: ["image", "imagepath", "画像", "写真", "labelimage"],
    price: ["price", "価格", "値段"],
    brewery: ["brewery", "酒蔵", "蔵元", "酒造", "醸造元", "shuzou", "breweryname"],
    flavor: ["flavor", "味わい", "コメント", "説明", "メモ", "description", "tastingnote", "note"],
    temperature: ["temperature", "温度", "おすすめ温度", "飲み方", "servingtemp", "recommendedtemp"],
    type: ["type", "タイプ", "分類", "系統", "tsukuri", "category", "style"],
    alcohol: ["alcohol", "度数", "アルコール度数", "abv", "alc"],
    polish: ["polish", "精米歩合", "seimai", "ricepolish"],
    pairing: ["pairing", "ペアリング", "合わせたいもの", "つまみ", "おすすめ料理", "foodpairing", "pairingnote"],
    published: ["published", "公開", "掲載", "表示", "status", "visible"],
    orderEnabled: ["orderenabled", "注文受付", "注文可", "order", "ordering"],
    soldOut: ["soldout", "売切れ", "売り切れ", "在庫切れ"],
    hiire: ["hiire", "火入れ"],
    sakamai: ["sakamai", "酒米", "rice"],
    prefecture: ["prefecture", "都道府県", "産地", "origin"],
  },
};

const sakeLookup = {
  冩樂: {
    aliases: ["写楽", "冩樂(写楽)"],
    brewery: "宮泉銘醸",
    prefecture: "福島",
    flavor:
      "甘味と酸味が綺麗に調和し、米の旨味も感じられる味わい。口の中にほのかに香る余韻が楽しめる定番の純米吟醸。",
    temperature: "雪冷え(5℃前後)",
    type: "純米吟醸",
    alcohol: "16%",
    polish: "50%",
    pairing: ["和食", "郷土料理", "松前漬"],
  },
  "風の森 ALPHA 1": {
    aliases: ["風の森ALPHA1", "風の森 alpha1", "風の森 ALPHA1", "風の森 次章への扉"],
    brewery: "油長酒造",
    prefecture: "奈良",
    flavor: "低アルコールでも果実感と密度があり、みずみずしい酸で軽快に飲める一本。",
    temperature: "よく冷やして",
    type: "菩提酛",
    alcohol: "13%",
    polish: "70%",
    pairing: ["前菜", "白身魚", "軽い揚げ物"],
  },
  "横山五十 WHITE": {
    aliases: ["横山五十 WHITE うすにごり生", "横山五十 white", "横山五十 うすにごり生"],
    brewery: "重家酒造",
    prefecture: "長崎",
    flavor: "マスカットを思わせるみずみずしい香りと、ジューシーな甘みが出るタイプ。",
    temperature: "冷酒",
    type: "純米大吟醸",
    alcohol: "16%",
    polish: "50%",
    pairing: ["白身魚カルパッチョ", "和食", "洋食"],
  },
  "横山五十 うすにごり 純米大吟醸": {
    aliases: ["横山五十 WHITE うすにごり生", "横山五十 white", "横山五十 うすにごり生"],
    brewery: "重家酒造",
    prefecture: "長崎",
    flavor: "マスカットを思わせるみずみずしい香りと、ジューシーな甘みが出るタイプ。",
    temperature: "冷酒",
    type: "純米大吟醸",
    alcohol: "16%",
    polish: "50%",
    pairing: ["白身魚カルパッチョ", "和食", "洋食"],
  },
};
